### ISSUE TITLE
Browser hangs on loading screen

### ISSUE THREAD

**Issue by arthem1990** [justdanpo/VivaldiHooks#48]
It was fine in summer but recently I updated Vivaldi and this repo now causes the browser to hang on the loading screen. I reinstalled all from scratch but here were are:

`[89777:89777:1002/125701.769709:ERROR:CONSOLE(378)] "TypeError: Object(...) is not a function", source: chrome-extension://mpognobbkildjkofajifpdfhcoklimli/vendor-bundle.js (378)
[89777:89777:1002/125701.786616:ERROR:CONSOLE(0)] "Error handling response: TypeError: Object(...) is not a function
    at chrome-extension://mpognobbkildjkofajifpdfhcoklimli/bundle.js:1:917177
    at _e.getInputFieldValue (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/bundle.js:1:917272)
    at _e.render (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/bundle.js:1:927042)
    at Ai (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/vendor-bundle.js:378:62954)
    at Oi (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/vendor-bundle.js:378:62749)
    at xi (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/vendor-bundle.js:378:66587)
    at Bo (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/vendor-bundle.js:378:90412)
    at Wo (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/vendor-bundle.js:378:90796)
    at ws (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/vendor-bundle.js:378:97824)
    at Os (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/vendor-bundle.js:378:97204)", source: chrome-extension://mpognobbkildjkofajifpdfhcoklimli/browser.html (0)
[89777:89777:1002/125701.806073:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Object(...) is not a function", source: chrome-extension://mpognobbkildjkofajifpdfhcoklimli/bundle.js (1)
[89777:89777:1002/125701.820905:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: The message port closed before a response was received.", source: chrome-extension://mpognobbkildjkofajifpdfhcoklimli/browser.html (0)`

Unrelated, but not worth creating another issue. It is required to cd to the proper dir in the script :

installhooks.sh
`#!/bin/sh

cp vivaldi/jdhooks.js /opt/vivaldi/resources/vivaldi/jdhooks.js
cp -r vivaldi/hooks /opt/vivaldi/resources/vivaldi/hooks

>>>>>>>>>>>> cd /opt/vivaldi/resources/vivaldi <<<<<<<<<<<<<<<

if ! grep -q "jdhooks.js" browser.html; then
        sed -i '/src="bundle.js"/i \ \ \ \ <script src="jdhooks.js"></script>' browser.html
fi`

**Comment by justdanpo** [comment]
Have you updated VivaldiHooks too?

**Comment by arthem1990** [comment]
That is correct. I have recloned the repo to double-check:
Vivaldi 3.4.2066.76 (Stable channel) (64-bit)
Manjaro 20.1.1

**Comment by tiosgz** [comment]
And are you sure you've replaced all the files in the `/opt/vivaldi/` folder? It's better to `sudo rm -rf /opt/vivaldi/resources/vivaldi/jdhooks.js /opt/vivaldi/resources/vivaldi/hooks/`, then re-copy all the files.

**Comment by arthem1990** [comment]
Thanks a lot, I have missed the fact of how `cp -r vivaldi/hooks /opt/vivaldi/resources/vivaldi/hooks` command works if the destination folder exists. So it was creating a nested directory and putting the files there. And I was too lazy to check manually. Solved :)
