### ISSUE TITLE
speeddial-shortcuts.js not working anymore from Vivaldi 4.0.2312.7

### ISSUE THREAD

**Issue by ian-coog** [justdanpo/VivaldiHooks#68]
error from the devtools console

   Error handling response: TypeError: vivaldi.jdhooks.require(...).getSpeeddialFolders is not a function
    at openSpeedDialItem (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/hooks/speeddial-shortcuts.js:23:63)
    at action (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/hooks/speeddial-shortcuts.js:41:31)
    at g (chrome-extension://mpognobbkildjkofajifpdfhcoklimli/bundle.js:1:294581)
    at chrome-extension://mpognobbkildjkofajifpdfhcoklimli/bundle.js:1:297620
    at chrome-extension://mpognobbkildjkofajifpdfhcoklimli/bundle.js:1:297627

**Comment by ian-coog** [comment]
Thanks, that fixes it.
